Chapter 9 - Working with Forms
ViolaRafael/shop pull request #2
Opened 2022-12-20 17:05 UTC by ViolaRafael

- Opção adicionada de Gerenciar produtos: Editar produtos existentes, remover produtos e criar novos produtos.
- Opção adicionada de prevenir remover produtos acidentalmente do carrinho e dos produtos(gerenciar produtos).

2022-12-20 17:07 UTC, PedroRaposoPMA commented
The pull request description should be in English.

2022-12-20 17:11 UTC, PedroRaposoPMA requested changes

2022-12-20 17:11 UTC, PedroRaposoPMA commented on lib/components/app_drawer.dart
> +            title: const Text('Bem vindo Usuário!'),
Use pt-pt (utilizador)

2022-12-20 17:11 UTC, PedroRaposoPMA commented on lib/components/cart_item.dart
> +            content: const Text('Quer Remover o tem do carrinho?'),
Missing connector (o `que` tem)

2022-12-20 17:11 UTC, PedroRaposoPMA commented on lib/models/product_list.dart
> +  void saveProduct(Map<String, Object> data) {
Add documentation

2022-12-20 17:11 UTC, PedroRaposoPMA commented on lib/models/product_list.dart
> +  void updateProduct(Product product) {
Add documentation

2022-12-20 17:11 UTC, PedroRaposoPMA commented on lib/models/product_list.dart
> +  void removeProduct(Product product) {
Add documentation

2022-12-20 17:18 UTC, samuelcpedro requested changes

2022-12-20 17:18 UTC, samuelcpedro commented on lib/components/cart_item.dart
> +            content: const Text('Quer Remover o tem do carrinho?'),
Update to 'Quer remover o item do carrinho?'

2022-12-21 11:08 UTC, PedroRaposoPMA approved these changes

2022-12-21 11:14 UTC, merged